return { "mrjones2014/smart-splits.nvim",
  config = true,
  keys = {
    {'<A-h>', function() require('smart-splits').resize_left() end, desc = "Resize Split Left"},
    {'<A-j>', function() require('smart-splits').resize_down() end, desc = "Resize Split Down"},
    {'<A-k>', function() require('smart-splits').resize_up() end, desc = "Resize Split Up"},
    {'<A-f>', function() require('smart-splits').resize_right() end, desc = "Resize Split Right"},
    {'<C-h>', function() require('smart-splits').move_cursor_left() end, desc = "Move To Split on the Left"},
    {'<C-j>', function() require('smart-splits').move_cursor_down() end, desc = "Move To Split Below Current"},
    {'<C-k>', function() require('smart-splits').move_cursor_up() end, desc = "Move To Split Above Current"},
    {'<C-l>', function() require('smart-splits').move_cursor_right() end, desc = "Move To Split on the Right"},
    {'<<leader><leader>-h>', function() require('smart-splits').swap_buf_left() end, desc = "Swap With Window on Left"},
    {'<<leader><leader>-j>', function() require('smart-splits').swap_buf_down() end, desc = "Swap With Window Below"},
    {'<<leader><leader>-k>', function() require('smart-splits').swap_buf_up() end, desc = "Swap With Window Above"},
    {'<<leader><leader>-l>', function() require('smart-splits').swap_buf_right() end, desc = "Swap With Window on Right"},
  },
}