#!/bin/bash

export PATH="$HOME/.local/bin:$PATH"

if [ -n "${CREDENTIALS_DIRECTORY:-}" ] && [ -f "$CREDENTIALS_DIRECTORY/GH_TOKEN" ]; then
export GH_TOKEN="$(<"$CREDENTIALS_DIRECTORY/GH_TOKEN")"
fi

# Set up fzf key bindings and fuzzy completion
eval "$(fzf --bash)"
# properly setup environment variables for lua
eval $(luarocks path --bin)

eval "$(starship init bash)"
