[Distribution]
Distribution=arch

[Output]
Format=directory
OutputDirectory=mkosi.output

[Content]
Packages=base
         sudo
         git
         curl
         bash
         neovim
         chezmoi
         nodejs
         npm
         github-cli
         fzf
         lua
         luarocks
         starship
	 debugedit
	 fakeroot
	 cargo
	 pkgconfig

[Build]
WithNetwork=yes
