[Distribution]
Distribution=arch

[Output]
Format=directory
OutputDirectory=mkosi.output
CacheDirectory=mkosi.cache

[Content]
Packages=base
         sudo
         git
         curl
         bash
         neovim
         chezmoi
         nodejs
         npm
         github-cli
         fzf
         lua
         luarocks
         starship
	 debugedit
	 fakeroot
	 cargo
	 pkgconfig

ExtraTrees=..:/srv/chezmoi-source

[Build]
WithNetwork=yes
