[Distribution]
Distribution=arch

[Output]
Format=directory
OutputDirectory=mkosi.output

[Content]
Packages=base
         sudo
         git
         curl
         bash
         neovim
         chezmoi
         nodejs
         npm
         cargo
         openssl
         clang
         github-cli
         fzf
         lua
         luarocks
         starship
ExtraTrees=..:/home/agent/.local/share/chezmoi

[Build]
WithNetwork=yes
