general {
    lock_cmd = hyprlock                        # run when a lock signal is received
    unlock_cmd = notify-send "Unlocked"        # hyprlock handles unlock itself; this is a no-op hook
    before_sleep_cmd = notify-send "Zzz"    # command ran before sleep
    after_sleep_cmd = notify-send "Awake!"  # command ran after sleep
    ignore_dbus_inhibit = false             # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
    ignore_systemd_inhibit = false          # whether to ignore systemd-inhibit --what=idle inhibitors
}

listener {
    timeout = 300                            # 5min: warn
    on-timeout = notify-send "You are idle!"
    on-resume = notify-send "Welcome back!"
}

listener {
    timeout = 360                            # 6min: lock
    on-timeout = hyprlock
}

listener {
    timeout = 600                            # 10min: suspend
    on-timeout = systemctl suspend
}
