vim.pack.add({
  "https://github.com/folke/flash.nvim",
  "https://github.com/stevearc/oil.nvim",
  "https://github.com/mrjones2014/smart-splits.nvim",
})

require("flash").setup()
vim.keymap.set({ "n", "x", "o" }, "<leader>j", function()
  require("flash").jump()
end, { desc = "Flash Jump" })
vim.keymap.set({ "n", "x", "o" }, "<leader>J", function()
  require("flash").treesitter()
end, { desc = "Flash Treesitter" })
vim.keymap.set("o", "r", function()
  require("flash").remote()
end, { desc = "Flash Remote" })
vim.keymap.set({ "o", "x" }, "R", function()
  require("flash").treesitter_search()
end, { desc = "Flash Treesitter Search" })
vim.keymap.set("c", "<c-s>", function()
  require("flash").toggle()
end, { desc = "Flash Toggle" })

require("oil").setup()
vim.keymap.set("n", "<leader>O", "<cmd>Oil<cr>", { desc = "Open Oil" })

require("smart-splits").setup()
vim.keymap.set("n", "<c-h>", function()
  require("smart-splits").move_cursor_left()
end)
vim.keymap.set("n", "<c-j>", function()
  require("smart-splits").move_cursor_down()
end)
vim.keymap.set("n", "<c-k>", function()
  require("smart-splits").move_cursor_up()
end)
vim.keymap.set("n", "<c-l>", function()
  require("smart-splits").move_cursor_right()
end)
vim.keymap.set("n", "<A-h>", function()
  require("smart-splits").resize_left()
end)
vim.keymap.set("n", "<A-j>", function()
  require("smart-splits").resize_down()
end)
vim.keymap.set("n", "<A-k>", function()
  require("smart-splits").resize_up()
end)
vim.keymap.set("n", "<A-l>", function()
  require("smart-splits").resize_right()
end)
vim.keymap.set("n", "<leader><leader>h", function()
  require("smart-splits").swap_buf_left()
end)
vim.keymap.set("n", "<leader><leader>j", function()
  require("smart-splits").swap_buf_down()
end)
vim.keymap.set("n", "<leader><leader>k", function()
  require("smart-splits").swap_buf_up()
end)
vim.keymap.set("n", "<leader><leader>l", function()
  require("smart-splits").swap_buf_right()
end)
